apiVersion: v1
kind: ConfigMap
metadata:
 name: payment
 namespace: roboshop
data:
    CART_HOST: "cart"
    CART_PORT: "8080"
    USER_HOST: "user"
    USER_PORT: "8080"
    AMQP_HOST: "rabbitmq"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: roboshop
  labels:
     project: roboshop
     tier: db
     component: payment
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3AK
  AMQP_PASS: cm9ib3Nob3AxMjMK
---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: payment
 namespace: roboshop
spec:
 replicas: 1

 selector:
  matchLabels:
     project: roboshop
     tier: backend
     component: payment
  ##pod defination
  template:
   metadata: 
    labels:
     project: roboshop
     tier: backend
     component: payment
   spec:
    containers:
     - name: payment
       image: srikanth865/payment:v1
       ports:
        - name: liveness-port
          containerPort: 8080
#Because ports, startupProbe, readinessProbe, livenessProbe, and envFrom are all configuration fields of the same container.
       startupProbe: #is the container done with booting
          httpGet:
            path: /health  #health check
            port: liveness-port
            # we are giving 2 minutes to start the application,if not will say its failure for booting
          failureThreshold: 12
          periodSeconds: 10
       readinessProbe: # this probe say Can I send traffic to it,if shipping not ready,removes that Pod from the Service's available endpoints.
          #k8s is continuously checking wheter pod/container is ready or not
          #This is especially useful because Shipping depends cart&Mysql
          httpGet:
            path: /health
            port: liveness-port
          periodSeconds: 10

       livenessProbe: #Is it still working/alive? 
      #suppose shipping starts successfully, but later the application gets stuck
      #liveness probe detects that if it is no longer healthy, and Kubernetes can restart the container.
          httpGet:
            path: /health
            port: liveness-port
          periodSeconds: 10 

       envFrom: #envfrom is list of task doing it may be one or many in list so we give  - 
        - configMapRef:
           name: payment
        - secretRef:
            name: payment
---
apiVersion: v1
kind: Service
metadata:
 name: payment
 namespace: roboshop
spec:
 selector:
  #this selector  service labels going to match the payment pod labels
     project: roboshop
     tier: backend
     component: payment
 ports:
  - protocol: TCP
    port: 8080 #serviceport
    targetPort: 8080  #container port

 