apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  # labels related to deployment resource its for jist reference
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  replicas: 1
  selector:  #Tells the Deployment controller which Pods to manage (matching the labels).
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb
  # Pod defination
  template:  #The blueprint used to create new Pods, defining the container name, image, and ports.
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: srikanth865/mongodb:v1
---
#service file which is used to for connecting pods and also The Service provides networking to those Pods:
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  # servicer labels
  labels:
      project: roboshop
      tier: db
      component: mongodb
spec:
  # Service uses the below labels to select the pods
  selector:
      project: roboshop
      tier: db
      component: mongodb
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port



#### As i used in docker as docker build -t mongodb:v1 . now i use as 4.0.0
# Yes. If previously you used:

# docker build -t mongodb:v1 .

# then v1 was simply your image tag.

# For example:

# mongodb:v1
#    │     │
#    │     └── tag you created
#    └──────── image/repository name

# If you later pushed it to Docker Hub as:

# docker tag mongodb:v1 srikanth865/mongodb:v1
# docker push srikanth865/mongodb:v1

######### then Kubernetes could use:  ##############

# image: srikanth865/mongodb:v1
# In your current setup

# You changed the tag to:

# docker build -t srikanth865/mongodb:4.0.0 .

# So:

# v1       → your old image tag
# 4.0.0    → your new image tag

# Neither v1 nor 4.0.0 tells you the MongoDB software version.

# Your actual MongoDB version is determined by:

# FROM mongo:7.0

# So your current image is essentially:

# srikanth865/mongodb:4.0.0
#           ↓
#       built from
#           ↓
#        mongo:7.0