apiVersion: v1
kind: Secret
metadata:
 name: mysql
 namespace: roboshop
 labels:
    project: roboshop
    tier: db
    component: mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "RoboShop@1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
 namespace: roboshop
 labels:
    project: roboshop
    tier: db
    component: mysql
spec:
 replicas: 1
 selector:
  matchLabels:
    project: roboshop
    tier: db
    component: mysql
 template:
  metadata:
   name: mysql
   namespace: roboshop
   labels:
    project: roboshop
    tier: db
    component: mysql
  spec:
   containers:
     - name: mysql
       image: srikanth865/mysql:v1
       envFrom:
        - secretRef:
           name: mysql
---

apiVersion: v1
kind: Service
metadata: 
 name: mysql
 namespace: roboshop
 labels:
    project: roboshop
    tier: db
    component: mysql
spec:
 selector:
    project: roboshop
    tier: db
    component: mysql
 ports: 
  - protocol: TCP
    port: 3306 
    targetPort: 3306